export const INIT_TODOS = 'INIT_TODOS'
export const NEW_TODO = 'NEW_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_ALL_TODOS = 'DELETE_ALL_TODOS';
export const DELETE_CHECKED_TODOS = 'DELETE_CHECKED_TODOS';
export const CHECK_TODO = 'CHECK_TODO';
export const CHECK_ALL_TODOS = 'CHECK_ALL_TODOS';
export const UNCHECK_ALL_TODOS = 'UNCHECK_ALL_TODOS';


export const INIT_NOTES = 'INIT_NOTES'

export const NEW_TEXT_NOTE = 'NEW_NOTE';
export const DELETE_TEXT_NOTE = 'DELETE_NOTE';
export const UPDATE_TEXT_NOTE = 'UPDATE_NOTE';

export const NEW_IMAGE_NOTE = 'NEW_IMAGE_NOTE';
export const DELETE_IMAGE_NOTE = 'DELETE_IMAGE_NOTE';
export const UPDATE_IMAGE_NOTE = 'UPDATE_IMAGE_NOTE';